In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("data/test_df.csv")
data.shape

(48744, 800)

In [10]:
app_data = data.iloc[:20]
app_data.drop(columns=["Unnamed: 0", "index","TARGET"], inplace=True)

/home/samuel/.local/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [11]:
app_data.to_csv("app/data/app_data.csv", index=False)

In [12]:
X = pd.read_csv("app/data/app_data.csv")

X = X.set_index("SK_ID_CURR")

X

,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,...,CC_NAME_CONTRACT_STATUS_Signed_MAX,CC_NAME_CONTRACT_STATUS_Signed_MEAN,CC_NAME_CONTRACT_STATUS_Signed_SUM,CC_NAME_CONTRACT_STATUS_Signed_VAR,CC_NAME_CONTRACT_STATUS_nan_MIN,CC_NAME_CONTRACT_STATUS_nan_MAX,CC_NAME_CONTRACT_STATUS_nan_MEAN,CC_NAME_CONTRACT_STATUS_nan_SUM,CC_NAME_CONTRACT_STATUS_nan_VAR,CC_COUNT
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
100001,1,0,0,0,135000.0,568800.0,20560.5,450000.0,0.018850,-19241,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100005,0,0,0,0,99000.0,222768.0,17370.0,180000.0,0.035792,-18064,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100013,0,1,0,0,202500.0,663264.0,69777.0,630000.0,0.019101,-20038,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,96.0
100028,1,0,0,2,315000.0,1575000.0,49018.5,1575000.0,0.026392,-13976,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49.0
100038,0,1,1,1,180000.0,625500.0,32067.0,625500.0,0.010032,-13040,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100042,1,1,0,0,270000.0,959688.0,34600.5,810000.0,0.025164,-18604,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84.0
100057,0,1,0,2,180000.0,499221.0,22117.5,373500.0,0.022800,-16685,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100065,0,0,0,0,166500.0,180000.0,14220.0,180000.0,0.005144,-9516,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100066,1,0,0,0,315000.0,364896.0,28957.5,315000.0,0.046220,-12744,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0
100067,1,1,0,1,162000.0,45000.0,5337.0,45000.0,0.018634,-10395,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,87.0
100074,1,0,0,0,67500.0,675000.0,25447.5,675000.0,0.003122,-23670,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100090,1,0,0,0,135000.0,261621.0,16848.0,216000.0,0.008019,-15524,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28.0
100091,1,0,0,0,247500.0,296280.0,23539.5,225000.0,0.018634,-12278,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100092,1,1,0,0,90000.0,360000.0,18535.5,360000.0,0.014520,-19687,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100106,0,0,0,0,180000.0,157500.0,7875.0,157500.0,0.031329,-12091,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100107,0,1,0,0,180000.0,296280.0,21690.0,225000.0,0.032561,-13563,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0
100109,1,1,0,0,202500.0,407520.0,26041.5,360000.0,0.007020,-19375,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,79.0
100117,0,1,0,0,90000.0,499221.0,22117.5,373500.0,0.003122,-22705,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100128,1,1,0,1,225000.0,431280.0,23526.0,360000.0,0.025164,-10962,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0
100141,1,1,0,0,175500.0,478498.5,46741.5,454500.0,0.010147,-17955,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN